dist: trusty
sudo: false

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install coverage

script:
  - coverage run --source=ndr_netcfg setup.py test

after_success:
  - codecov

